# -*- coding: utf-8 -*-
"""Kappa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O5d92SeLOPjZ9QgNdSQHR64qFW9JrglM
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.random.randint(8,10,(30,3))
y = np.random.randn(30,3)

def scatter(x,y,jitter=.75,errBar='std',facecolor='none',edgecolor='firebrick',alpha=1,s=50):
  np.random.seed(23)
  X = x + np.random.randn(*np.shape(x))*jitter/10
  plt.scatter(X,y,facecolor=facecolor,edgecolor=edgecolor,alpha=alpha,s=s)

scatter(x,y,1,alpha=.5)
plt.xlim(6,12)

